### ISSUE TITLE
FloatReferenceDrawer no longer works

### ISSUE THREAD

**Issue by christopherperry** [roboryantron/Unite2017#13]
I'm not sure when this broke but it currently does not work in Unity 2019.3.14.

```
property.FindPropertyRelative();
```

always returns `null`. I have `FloatReference` defined in my project and I also created an instance saved in my project.

Here's the problematic line:
https://github.com/roboryantron/Unite2017/blob/4594a006980a09c8231477c35a4bbc5aea0b57ed/Assets/Code/Variables/Editor/FloatReferenceDrawer.cs#L39

**Comment by christopherperry** [comment]
Hey @roboryantron, bumping this issue so you're aware. Is this broken in your work projects as well or did you fix it there?

**Comment by roboryantron** [comment]
Hey, I'm not getting the same result when testing in 2019.3.13. Have you
pulling a copy of the sample project alone and testing it to rule out any
local changes?

Also, this is a super simplified version based of of the concept of what I
built for the studio. The thing I use at work had way way more stuff to it.

**Comment by christopherperry** [comment]
Hmmm... I tried your example project and it works there. I copied the code for the FloatReference and the property drawer for that including your namespace and that works. I had copied without the namespace prior to this and it didn't want to work that way.

**Comment by christopherperry** [comment]
Closing, there doesn't appear to be a problem.
