### ISSUE TITLE
Inventory Demo

### ISSUE THREAD

**Issue by cemuka** [roboryantron/Unite2017#3]
Hi Ryan,

I am very happy to see new ScriptableObjects stuff. There are limited source when its come to architecture in unity. In your presentation demo I saw inventory in project root. Sadly, you had not enough time to show on unite event. I would like to see what you were to present about inventory.

Thank you

**Comment by prodigga** [comment]
+1

**Comment by LeafMountain** [comment]
https://github.com/roboryantron/Unite2017/tree/5f88315fceaf9104dc09ba062f62daa2cbdafa41/Assets/Code/Inventory

A link to an older commit. Still has the Inventory system! :D

**Comment by cemuka** [comment]
thank you! :D
