### ISSUE TITLE
Persistence (saving data)

### ISSUE THREAD

**Issue by prodigga** [roboryantron/Unite2017#5]
Maybe your inventory example would've shed some light on this. How does data remain persistant? (IE player Inventory)

**Comment by roboryantron** [comment]
There are 2 levels of persistence worth thinking about here. First is between scenes. We kind of get that for free with Scriptable Objects. The next is between play sessions. That can be easily solved by having a variable save and load through something like player prefs or whatever your serialization model is. 

It then needs to be up to the game logic to decide when each thing saves and loads, but it can be nice and modular to have each variable track their own save key.
