### ISSUE TITLE
ScriptableObjectsEvents on build, Android not working.

### ISSUE THREAD

**Issue by GuillermoDoradoVide** [roboryantron/Unite2017#7]
Hi!
I've been trying to implement a EventManager system with scriptableObjects following your system.
Using GameEventListener and GameEvents.

https://drive.google.com/open?id=10qbMMY9oPzcCfW6nZLAHugA6Q7ToXotX
https://drive.google.com/open?id=1LDdapYIDncnNL4M0TEmoaFqsWv2mUMeo
https://drive.google.com/open?id=140IufZd1ppF-rP8JUmnZ9uYXQb1PYfWr

On the editor it works perfectly, but when I build it in Android it doesnt work. It is as if the scriptableObjects weren't assigned, or are just null.
Also, debugging it in android I get warnings like:

- Script attached to 'CubeSampleDialogTriggerEvent' in scene '' is missing or no valid script is attached. (this is a scriptableGameEvent object)
- The referenced script on this Behaviour (Game Object '<null>') is missing!

I tested it building the sample project in android an it worked there, so could it be a problem with my Unity set up?
The implementation is for an VRDaydream game. Any ideas?

**Comment by roboryantron** [comment]
Hi Guillermo!

Without looking at the source I do not really think I could debug it. There
is nothing inherent to the system that is not compatible with Android, we
have shipped many titles on Android with this tech.

Some things that could cause errors like that:

   - Is the script defined in an Editor folder?
   - Is there a Script/class name mismatch?
   - Are there multiple classes in the script?
   - Are you caching anything with OnValidate that is not serializeable?

Hope this helps!

**Comment by GuillermoDoradoVide** [comment]
No (scriptableObjects) scripts are in an Editor Folder.
I've created some heritage classes from GameEvent --->
public class DialogOptionSelectedEvent : GameEvent
{
    public int dialogSelected;
    public int Dialog { get { return dialogSelected; } }
}

public class SetDialogSectionEvent : GameEvent
{
    private DialogOption dialogOption;
    public DialogOption DialogOption { get { return dialogOption; } }
    public void SetDialogOption(DialogOption newDialogOption)
    {
        dialogOption = newDialogOption;
    }

    private CharacterDialogOption characterDialogOption;
    public CharacterDialogOption CharacterDialogOption { get { return characterDialogOption; } }
    public void SetCharacterDialogOption(CharacterDialogOption newCharacterDialogOption)
    {
        characterDialogOption = newCharacterDialogOption;
    }
}
And also I use some scriptableObjects for storing data >>>

public class CharacterDialogOption : ScriptableObject {
    [Tooltip("The description for this section of the conversation")]
    public string dialogName;
    [Tooltip("The position in the conversation")]
    public int dialogOrder;
    public List<AudioClip> dialogs;
    public List<string> playerQuotes;
}

**Comment by GuillermoDoradoVide** [comment]
Okey, now It works! Seems that the scriptableObjects Assets created lost their reference to the class. But I don´t know how or why.

**Comment by roboryantron** [comment]
Glad to hear it works! Could be some met file / GUID confusion with renaming scripts that caused the break.
